### ISSUE TITLE
Question: is this package the right one for my use case?

### ISSUE THREAD

**Issue by CodingSpiderFox** [glebbash/nestjs-swagger-dto#13]
I am looking for a way to simplify my DTOs.

Currently, I am using class-validator and class-transformer decorators (e.g. IsOptional, IsString) to handle the validations of JSON payloads on POST requests as well as swagger annotations (ApiProperty, ApiPropertyOptional) withing those DTO classes.

My gut feeling tells me that this is quite error prone they way I am doing it

For example - this DTO:

```ts
import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { IsOptional, IsString } from 'class-validator';

export class MyDto {
  @ApiProperty({ example: 'the-lastname', description: 'Last name' })
  @IsString()
  lastName: string;

  @ApiPropertyOptional({
    type: 'string',
    example: 'birth-day',
    description: 'the birth day'
  })
  @IsString()
  @IsOptional()
  birthDay?: string;
}
```

If I wanted to change the birthDay to be required, I would have to
- remove the ? operator
- change ApiPropertyOptional to ApiProperty
- remove the IsOptional

It's easy to forget one of these steps and the things might break
- IsOptional and changing ApiPropertyOptional to ApiProperty is forgotten: swagger would not mark the field as required. User might send DTO with missing birthDay and not expect that the request will be denied with code 400

Change of field "birthDay" from type string to Date
- need to change @IsString to @IsDate
- need to change ApiPropertyOptional.type from string to date

Would this package solve my problem and save me from inconsistencies in my DTO definitions?

**Comment by glebbash** [comment]
Yes, this package was created to solve exactly this problem and it does it really well (being used in a decent number of production services).

It is able to handle most DTO definition cases and you'll very rarely need to fallback to `@nestjs/swagger` + `class-validator`.

**Comment by CodingSpiderFox** [comment]
That sounds great :) I will try it as soon as I find the time :)
