### ISSUE TITLE
canBeEmpty accepts only true or undefined

### ISSUE THREAD

**Issue by andersondanilo** [glebbash/nestjs-swagger-dto#14]
https://github.com/glebbash/nestjs-swagger-dto/blob/bb6c86f5f59bdd7383308e4fd06fa39d34ce0d4e/src/decorators/is-string.ts#L40

I noticed something about this line, the type should  accept "boolean | undefined" instead of just "true | undefined."

Also, I have a suggestion that I believe would be beneficial. Instead of using the minimum character validation, it might be worth considering the IsNotEmpty validation (allow the developer to choose the validation type). This way, when new code integrates with it, we can maintain the same error messages as before, and it won't affect the tests that are checking the error message. It's all about making things easier to work with and maintain!

**Comment by glebbash** [comment]
Thanks for reporting the issue @andersondanilo, @AaronTrazona.

The fix is included in [nestjs-swagger-dto@3.6.1](https://github.com/glebbash/nestjs-swagger-dto/releases/tag/v3.6.1).
