### ISSUE TITLE
accepts custom exceptionFactory

### ISSUE THREAD

**Issue by andersondanilo** [glebbash/nestjs-swagger-dto#15]
https://github.com/glebbash/nestjs-swagger-dto/blob/bb6c86f5f59bdd7383308e4fd06fa39d34ce0d4e/src/decorators/typed-headers.decorator.ts#L42

I'm really excited about this decorator! It would be awesome if it could accept a custom exception factory or even an entire ValidationPipe.

**Comment by glebbash** [comment]
Will this work for you #16?

**Comment by glebbash** [comment]
Added support for using custom `ValidationPipe` in [nestjs-swagger-dto@3.7.0](https://github.com/glebbash/nestjs-swagger-dto/releases/tag/v3.7.0):
```ts
@TypedHeaders({ validationPipe: new ValidationPipe({ transform: true }) })
```
