### ISSUE TITLE
startTime is not ISO8601 format error

### ISSUE THREAD

**Issue by Yetispapa** [glebbash/nestjs-swagger-dto#17]
Hi @glebbash,

I'm using your `nestjs-swagger-dto` package and I'm getting the error `"startTime is not ISO8601 format."` I don't understand why, because the `startTime` property in the request body is a string in ISO8601 format.

Here is my MyDto class:

```
export class MyDto {
  @IsDate({
    nullable: true,
    format: 'date-time',
  })
  startTime: Date | null;
}
```

Here is my Post request body:
JSON
```
{
  "startTime": "2023-10-24T16:13:58.325035"
}
```

Here is my controller code:

```
@Post()
async create(@Body() dto: MyDto) {
  // ...
}
```

I have a global validation pipe in my main.ts file:

```
app.useGlobalPipes(
  new ValidationPipe({
    forbidUnknownValues: true,
    transform: true,
  }),
);
```

I tried copying the `isDateString` function from the `nestjs-swagger-dto` package to my `MyDto.ts` file and adding some console logs before and inside the if statement:

```
if (!isDateString(value, { strict: true })) {
  // ...
}
```

Here is the output of the console logs:

```
// this is a string
2023-10-24T16:13:58.325035

// this is a date object
2023-10-24T14:13:58.325Z
```

It seems like the validation is correctly phrasing the string and after that it's trying to validate a date object, which was previously converted and this is of course not a string. This is why `isDateString` is failing.

I'm not sure if this is a problem with my code, NestJS, or the nestjs-swagger-dto package. Can you please help me? 

Thank you in advance

**Comment by glebbash** [comment]
Hello @Yetispapa,
I can't reproduce the results you provided, do you have latest versions of nest and this nestjs-swagger-dto?

The following works fine with versions used in dev-dependencies in this repository (tested on node 16 and 20):
```ts
import { Body, Controller, INestApplication, Post, ValidationPipe } from '@nestjs/common';
import { Test } from '@nestjs/testing';
import request from 'supertest';

import { IsDate } from './nestjs-swagger-dto';

export class MyDto {
  @IsDate({
    nullable: true,
    format: 'date-time',
  })
  startTime!: Date | null;
}

@Controller({ path: 'test', version: '1' })
export class TestController {
  @Post()
  async test(@Body() body: MyDto): Promise<string> {
    return body.startTime?.toDateString() ?? 'error';
  }
}

describe('minimal reproduction', () => {
  let app: INestApplication;

  beforeAll(async () => {
    const moduleRef = await Test.createTestingModule({
      controllers: [TestController],
    }).compile();

    app = moduleRef.createNestApplication();
    app.useGlobalPipes(
      new ValidationPipe({
        forbidUnknownValues: true,
        transform: true,
      })
    );
    await app.init();
  });

  it('works', async () => {
    await request(app.getHttpServer())
      .post('/test')
      .send({ startTime: '2023-10-24T16:13:58.325035' })
      .expect(201)
      .expect('Tue Oct 24 2023');
  });
});
```

**Comment by Yetispapa** [comment]
Hi there,

Thanks for your quick response! It was on my side.. I had another `ValidationPipe` in the `app.module.ts` like:

```
    {
      provide: APP_PIPE,
      useValue: new ValidationPipe({
        forbidUnknownValues: true,
        transform: true,
      }),
    },
```

That's why it was validated twice..

Thank you for providing the concise unit test, which allowed me to confirm that the fault is not in the package.

Awesome package by the way! I thins up my entities by a lot 👍
