### ISSUE TITLE
@Type from class-transformer is not working

### ISSUE THREAD

**Issue by Lindsay0214** [glebbash/nestjs-swagger-dto#18]
Hi, I'd like to ask why my code is not running as expected with the following code.

ExampleDto
```
import { IsNumber } from "nestjs-swagger-dto";

export class ExampleDto {
  @IsNumber({ description: "id" })
  id: number;
}
```

Response
```
{
    "code": "Bad Request",
    "message": "id must be a number conforming to the specified constraints"
}
```

I thought combining `class-transformer` and `class-validator` would define the types for me and perform transformations for the values of those fields, but it doesn't seem to be working?

and I tried below which was work
```
import { Type } from "class-transformer";
import { IsNumber } from "nestjs-swagger-dto";

export class ExampleDto {
  @Type(() => Number)
  @IsNumber({ description: "id" })
  id: number;
}
```

So is it that this package doesn't include the transformations by default, or am I missing something?

**Comment by glebbash** [comment]
Can you provide [minimal reproduction](https://en.wikipedia.org/wiki/Minimal_reproducible_example) or at least more information about your setup so that I can reproduce the behavior?

**Comment by Lindsay0214** [comment]
Not sure how to reprodece it on web, because I tried it on my local db and local server.

I put mininal code on [here](https://codesandbox.io/p/devbox/nest-users-forked-8t97yg?file=%2Fsrc%2Fexample%2Fcategories.dto.ts%3A7%2C15).

And this is my local api tester
<img width="1003" alt="截圖 2024-06-25 下午4 57 34" src="https://github.com/glebbash/nestjs-swagger-dto/assets/56778568/e12612c2-34cf-4ec4-a7fd-78d470d6a188">

**Comment by Lindsay0214** [comment]
Sorry, [here](https://codesandbox.io/p/devbox/nest-users-forked-8t97yg?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clxu5w9cz00073b776vbze03j%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clxu5w9cy00023b77mhbp83gg%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clxu5w9cy00043b77883zmv3u%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clxu5w9cz00063b775g6i97ef%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clxu5w9cy00023b77mhbp83gg%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxu5w9cy00013b770pi5m2tu%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clxu5w9cy00023b77mhbp83gg%2522%252C%2522activeTabId%2522%253A%2522clxu5w9cy00013b770pi5m2tu%2522%257D%252C%2522clxu5w9cz00063b775g6i97ef%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxu5w9cz00053b775nsw90z7%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522start%2522%252C%2522port%2522%253A3000%252C%2522path%2522%253A%2522%2522%257D%255D%252C%2522id%2522%253A%2522clxu5w9cz00063b775g6i97ef%2522%252C%2522activeTabId%2522%253A%2522clxu5w9cz00053b775nsw90z7%2522%257D%252C%2522clxu5w9cy00043b77883zmv3u%2522%253A%257B%2522id%2522%253A%2522clxu5w9cy00043b77883zmv3u%2522%252C%2522activeTabId%2522%253A%2522clxu5xx5d00243b78kq2v6yuz%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxu5w9cy00033b77gg7vio1g%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522start%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522npm%2520install%2520nestjs-swagger-dto%25403.8.0%2522%252C%2522id%2522%253A%2522clxu5xx5d00243b78kq2v6yuz%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)!

**Comment by glebbash** [comment]
Ok, I see the problem. If your DTOs are used with `@Query()` decorator Nest.js will keep all DTO properties as strings.

To fix that there is an option in `@IsNumber` and some other decorators called `stringified`.

So just update your example:
```ts
export class CategoriesDto {
  @IsNumber({ optional: true })
  categoryId: number;

  @IsString({ optional: true })
  keyword: string;
}
```

To this:

```ts
export class CategoriesDto {
  @IsNumber({ optional: true, stringified: true })
  categoryId: number;

  @IsString({ optional: true })
  keyword: string;
}
```

P.S: I didn't know this could be fixed with `@Type` decorator. I might look into that and update you if this lib will use it. But for now just use `stringified` option in `@Query` DTOs.

**Comment by Lindsay0214** [comment]
Thank you!!! I didn't quite understand that parameter in the documentation.

**Comment by glebbash** [comment]
Glad it worked 👍

I'll update the docs and check for `@Type` decorator usage sometime.

**Comment by glebbash** [comment]
Checked how the `@Type(() => Number)` decorator works, and it is not great. It will accept values like `" 1"` and `"1 "` which won't happen with `@Query` DTOs but should be rejected as bad input anyways.

`stringified` option provides strict validation using `isNumberString` from `class-validator`. Added field description to the inline TSDoc, hopefully it should be more noticable now.
